CC		= gcc
CPPFLAGS	=
CFLAGS		= `pkg-config --cflags gtk+-3.0`
CFLAGS		+= -Wall -Wextra -g
LDFLAGS		= `pkg-config --libs-only-L gtk+-3.0`
LDLIBS		= `pkg-config --libs-only-l --libs-only-other gtk+-3.0`

MediaPlayer.exe: MediaPlayer
